name: Check Classes

# Run every 5 minutes
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  trigger-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API endpoint
        run: |
          curl -X GET "https://student-engagement-pulse.vercel.app/api/cron?apiKey=${{ secrets.API_KEY }}"